// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADO-CQt1B9P6yMj8DrXdvLQr4S0SWv_Kk',
    appId: '1:203291514929:web:cd5daea8089992eefa9d10',
    messagingSenderId: '203291514929',
    projectId: 'ecommerce-f1328',
    authDomain: 'ecommerce-f1328.firebaseapp.com',
    storageBucket: 'ecommerce-f1328.firebasestorage.app',
    measurementId: 'G-WGYGY706TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMJHtNxBDHRE8Sh-fZgvVHb_Xqtnr53A',
    appId: '1:203291514929:android:40ab85a9142c77d5fa9d10',
    messagingSenderId: '203291514929',
    projectId: 'ecommerce-f1328',
    storageBucket: 'ecommerce-f1328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuR9zL7I9B6-wuYpeKzZq-sLPv_SEiEE',
    appId: '1:203291514929:ios:d8cba5ed63500809fa9d10',
    messagingSenderId: '203291514929',
    projectId: 'ecommerce-f1328',
    storageBucket: 'ecommerce-f1328.firebasestorage.app',
    iosBundleId: 'com.example.flutterEjercicio1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLuR9zL7I9B6-wuYpeKzZq-sLPv_SEiEE',
    appId: '1:203291514929:ios:d8cba5ed63500809fa9d10',
    messagingSenderId: '203291514929',
    projectId: 'ecommerce-f1328',
    storageBucket: 'ecommerce-f1328.firebasestorage.app',
    iosBundleId: 'com.example.flutterEjercicio1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADO-CQt1B9P6yMj8DrXdvLQr4S0SWv_Kk',
    appId: '1:203291514929:web:fc9a22ba65787addfa9d10',
    messagingSenderId: '203291514929',
    projectId: 'ecommerce-f1328',
    authDomain: 'ecommerce-f1328.firebaseapp.com',
    storageBucket: 'ecommerce-f1328.firebasestorage.app',
    measurementId: 'G-4PFWDB2QL1',
  );
}
